core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
]

#Configuración extendida para mostrar las imágenes en modo debug
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import HomeView,CreateUserView, logout_view, LoginUserView
app_name= 'user'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateUserView.as_view(), name='create_user'),
    path('logout/', logout_view, name='logout'),
    path('login/', LoginUserView.as_view(), name='login'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    image = models.ImageField(upload_to = 'users')

    def save(self, *args, **kwargs):
        # Si se proporciona una contraseña y no está encriptada, encriptarla
        if self.password and not self.password.startswith('pbkdf2_'):
            self.set_password(self.password)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"
        ordering = ["-date_joined"]
        db_table = "tabla_usuario"

user/forms.py
from django import forms
from .models import User

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password','image']

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView

from django.contrib.auth import logout, login
from django.contrib.auth import authenticate

from .forms import CreateUserForm

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render (request, 'home.html', context)


class CreateUserView(CreateView):
    def get(self, request, *args, **kwargs):
        form = CreateUserForm()
        context = {
            'form': form
        }
        return render(request, 'user/create_user.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = CreateUserForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('user:home')
        else:
            form = CreateUserForm()
        return render(request, 'user/create_user.html', {'form': form})
    

class LoginUserView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render (request, 'user/login_user.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            print(username, password)
            print(user)
            if user is not None:
                login(request, user) 
                return redirect('user:home')
            else:
                context = {'error': 'Usuario o contraseña incorrecta'}
        else:
            context = {'error': 'Método no permitido'}

        return render(request, 'user/login_user.html', context)

def logout_view(request):
    logout(request)
    return redirect('user:home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/home.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/create_user.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/login_user.css' %}" rel="stylesheet" type="text/css"/>
    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% if request.user.is_authenticated %}
        <nav class='navbar'>
            <ul>
                <li><a href="{% url 'user:logout' %}">Cerrar sesión</a></li>
            <ul>
        </nav>
        <p>Bienvenido, {{ request.user.username }}</p>
        
    {% else %}
        <nav class='navbar'>
            <ul>
                <li><a href="{% url 'user:login' %}">Iniciar sesión</a></li>
                <li><a href="{% url 'user:create_user' %}">Registrarse</a></li>
            </ul> 
        </nav>
        
    {% endif %}



{% endblock content %}

templates/user/create_user.html
{% extends 'base.html' %}

{% block content %}
create user 
<div class="content-form">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_first_name">Nombre:</label>
            {{ form.first_name }}
        </div>
        <div class="form-group">
            <label for="id_last_name">Apellido:</label>
            {{ form.last_name }}
        </div>
        <div class="form-group">
            <label for="id_username">Usuario:</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="id_email">Correo:</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label for="id_password">Contraseña:</label>
            {{ form.password }}
        </div>
        <div class="form-group">
            <label for="id_image">Foto de perfil:</label>
            {{ form.image }}
        </div>
        <button class="btn-submit" type="submit">Crear</button>
    </form>
</div>


{% endblock content %}

templates/user/login_user.html
{% extends 'base.html' %}

{% block content %}


<form method="POST" class="content-form">
    {{ error }}
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Usuario:</label>
        <input type="text" name="username" id="username" class="form-control" placeholder="Ingresar usuario">
    </div>
    <div class="form-group">
        <label for="password">Contraseña:</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Ingresar contraseña">
    </div>
    <button class="btn-submit" type="submit">Iniciar sesión</button>
</form>
{% endblock content %}